# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/340/bin/cmake

# The command to remove a file.
RM = /snap/cmake/340/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/thomas/Documents/github/Raytracer/projet/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/thomas/Documents/github/Raytracer/projet/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/340/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/340/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thomas/Documents/github/Raytracer/projet/src/CMakeFiles /home/thomas/Documents/github/Raytracer/projet/src/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thomas/Documents/github/Raytracer/projet/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lray

# Build rule for target.
lray: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lray
.PHONY : lray

# fast build rule for target.
lray/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lray.dir/build.make CMakeFiles/lray.dir/build
.PHONY : lray/fast

Raytracer.o: Raytracer.cpp.o

.PHONY : Raytracer.o

# target to build an object file
Raytracer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lray.dir/build.make CMakeFiles/lray.dir/Raytracer.cpp.o
.PHONY : Raytracer.cpp.o

Raytracer.i: Raytracer.cpp.i

.PHONY : Raytracer.i

# target to preprocess a source file
Raytracer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lray.dir/build.make CMakeFiles/lray.dir/Raytracer.cpp.i
.PHONY : Raytracer.cpp.i

Raytracer.s: Raytracer.cpp.s

.PHONY : Raytracer.s

# target to generate assembly for a file
Raytracer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lray.dir/build.make CMakeFiles/lray.dir/Raytracer.cpp.s
.PHONY : Raytracer.cpp.s

Vector.o: Vector.cpp.o

.PHONY : Vector.o

# target to build an object file
Vector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lray.dir/build.make CMakeFiles/lray.dir/Vector.cpp.o
.PHONY : Vector.cpp.o

Vector.i: Vector.cpp.i

.PHONY : Vector.i

# target to preprocess a source file
Vector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lray.dir/build.make CMakeFiles/lray.dir/Vector.cpp.i
.PHONY : Vector.cpp.i

Vector.s: Vector.cpp.s

.PHONY : Vector.s

# target to generate assembly for a file
Vector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lray.dir/build.make CMakeFiles/lray.dir/Vector.cpp.s
.PHONY : Vector.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lray"
	@echo "... Raytracer.o"
	@echo "... Raytracer.i"
	@echo "... Raytracer.s"
	@echo "... Vector.o"
	@echo "... Vector.i"
	@echo "... Vector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

